# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PR check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x.x

      - name: Restore dependencies
        run: |
          dotnet restore ConsoleApp7Plus
          dotnet restore ConsoleApp7Plus.Tests

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Build
        run: dotnet build --no-restore
